<?php
/**
* Implements hook_block_info().
*/
function teamwork_blocks_block_info() {
  $blocks = array();

  $blocks['teamwork_people_block'] = array(
    'info' => t('Teamwork: People Block'),
  );
  
  $blocks['teamwork_tasklists_block'] = array(
    'info' => t('Teamwork: Tasklist Block'),
  );

  return $blocks;
}

/**
* Implements hook_block_view().
*/
function teamwork_blocks_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'teamwork_people_block':
	 //if(user_access('access content')){ //good idea to check user perms here
      $block['subject'] = t('My People');
      $block['content'] = teamwork_people_block_content();
      break;
	  
	case 'teamwork_tasklists_block':
	  $block['subject'] = t('My Tasklists');
	  $block['content'] = teamwork_tasklists_block_content();
	break;
  }

  return $block;
}

function teamwork_people_block_content() {
$items = array();
$items['people'] = array('#markup' => $result);
  //send to template
  return theme('teamwork_people_block_content', array('items' => $items));
}

function teamwork_tasklists_block_content() {
$items = array();
$items['tasklists'] = array('#markup' => $result);
  //send to template
  return theme('teamwork_tasklists_block_content', array('items' => $items));
}

//here you are registering your default tpl for the above block 
function teamwork_blocks_theme() {   
  $module_path = drupal_get_path('module', 'teamwork_blocks');
  $base = array(
    'path' => "$module_path/theme",   
  );
  return array(
    'teamwork_people_block_content' => $base + array(
      'template' => 'teamwork_people_block',  //leave off .tpl.php
      'variables' => array('items' => NULL,),
    ), 
    'teamwork_tasklists_block_content' => $base + array(
      'template' => 'teamwork_tasklists_block',  //leave off .tpl.php
      'variables' => array('items' => NULL,),
    ), 	
  ); 
}